php-version = "8.4.0"

[source]
paths = ["src", "tests"]
includes = ["vendor"]
excludes = []

[formatter]
print-width = 120
null-type-hint = "question"

[linter]
integrations = ["tempest", "phpunit"]

[linter.rules]
literal-named-argument = { enabled = false }
parameter-type = { ignore-closure = true, ignore-arrow-function = true }
return-type = { ignore-arrow-function = true }
no-boolean-flag-parameter = { enabled = false }
assertion-style = { style = "$this"}
class-name = { enabled = false}
interface-name = { enabled = false}
trait-name = { enabled = false}
too-many-methods = { enabled = false }
no-else-clause = { enabled = false }
excessive-parameter-list = { enabled = false }
halstead = { enabled = false }
kan-defect = { enabled = false }
cyclomatic-complexity = { enabled = false }
yoda-conditions = { enabled = false }
no-redundant-file = { enabled = false }

[analyzer]
